-- 插入机器数据
INSERT INTO `may` (`id`, `khu_vuc`, `ten_may`, `ban_do_may`, `vi_tri_loi`) VALUES
(74, 'Điều hòa', 'DH101I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(75, 'Điều hòa', 'DH102I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(76, 'Điều hòa', 'DH103I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(77, 'Điều hòa', 'DH104I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(78, 'Điều hòa', 'DH105I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(79, 'Điều hòa', 'DH106I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(80, 'Điều hòa', 'DH107I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(81, 'Điều hòa', 'DH108I - Xưởng in - 240.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(82, 'Điều hòa', 'DH109I - Phòng CTP - 120.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(83, 'Điều hòa', 'DH110I - Phòng R706UV - 120.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(84, 'Điều hòa', 'DH111I - Phòng R706UV - 120.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(85, 'Điều hòa', 'DH112I - Phòng R706UV - 120.000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(86, 'Điều hòa', 'DH101V - Phòng laze - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(87, 'Điều hòa', 'DH102V - Phòng khuôn - 28000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(88, 'Điều hòa', 'DH103V - Phòng khuôn - 28000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(89, 'Điều hòa', 'DH104V - Phòng lưới - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(90, 'Điều hòa', 'DH105V - Phòng Cơ Điện -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(91, 'Điều hòa', 'DH101K - Kho thành phẩm - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(92, 'Điều hòa', 'DH102K - Kho thành phẩm - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(93, 'Điều hòa', 'DH103K - Kho vật tư - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(94, 'Điều hòa', 'DH104K - Kho keo - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(95, 'Điều hòa', 'DH105K - Kho keo - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(96, 'Điều hòa', 'DH106K - Văn phòng kho - 12000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(97, 'Điều hòa', 'DH107K - Kho lô - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(98, 'Điều hòa', 'DH108K - Kho lô - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(99, 'Điều hòa', 'DH101S - Phòng sần -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(100, 'Điều hòa', 'DH102S - Phòng sần -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(101, 'Điều hòa', 'DH103S - Phòng sần -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(102, 'Điều hòa', 'DH201 - Văn phòng SX - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(103, 'Điều hòa', 'DH202 - Phòng họp SX - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(104, 'Điều hòa', 'DH201V - Phòng giám đốc - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(105, 'Điều hòa', 'DH202V - Phòng họp - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(106, 'Điều hòa', 'DH203V - Phòng làm việc chung - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(107, 'Điều hòa', 'DH204V - Phòng làm việc chung - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(108, 'Điều hòa', 'DH205V - Phòng làm việc chung - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(109, 'Điều hòa', 'DH206V - Phòng làm việc chung - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(110, 'Điều hòa', 'DH207V - Phòng Kỹ thuật - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(111, 'Điều hòa', 'DH212V - Phòng Kỹ thuật -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(112, 'Điều hòa', 'DH208V - Phòng QC - 34000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(113, 'Điều hòa', 'DH209V - Phòng LAB - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(114, 'Điều hòa', 'DH211V - P. Cắt mẫu -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(115, 'Điều hòa', 'DH210V - Nhà ăn - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(116, 'Điều hòa', 'DH301V - Phòng máy tính - 9000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(117, 'Điều hòa', 'DH302V - Phòng họp - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(118, 'Điều hòa', 'DH303V - Phòng phó giám đốc - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(119, 'Điều hòa', 'DH304V - Phòng nhân sự, kế toán - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(120, 'Điều hòa', 'DH207V - Phòng nhân sự, kế toán - 48000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(121, 'Điều hòa', 'DH306V - Phòng thờ -', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(122, 'Điều hòa', 'DH301 - Tổ hoàn thiện - 12000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(123, 'Điều hòa', 'DH302 - Tổ hoàn thiện - 12000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(124, 'Điều hòa', 'DH303 - Tổ Hộp cứng - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(125, 'Điều hòa', 'DH304 - Tổ Hộp cứng - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'),
(126, 'Điều hòa', 'DH305 - Tổ Hộp cứng - 24000 BTU', '', 'Hệ thống điện, Hệ thống làm lạnh, Hệ thống nước'); 